version: '3.8'

services:
  # 🗄️ BASE DE DATOS
  mongo:
    image: mongo:latest
    container_name: helpdesk_mongo
    restart: always
    ports:
      - "27018:27017" # ¡OJO! Lo sacamos por el 27018 para que no pelee con otras bases de datos
    volumes:
      - mongo_data:/data/db

  # ⚙️ BACKEND (Python)
  backend:
    build: ./backend
    container_name: helpdesk_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend/storage:/app/storage

  # 🌐 FRONTEND (React/Vite)
  frontend:
    build: ./frontend
    container_name: helpdesk_frontend
    restart: always
    ports:
      - "8080:80" # ¡OJO! Tu página ahora vivirá en el puerto 8080
    depends_on:
      - backend

volumes:
  mongo_data: